before_script:
- psql -c 'create database olympics_api_test;' -U postgres
language: ruby
rvm:
- 2.4.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
services: postgresql
deploy:
  provider: heroku
  api_key:
    secure: UJoU5rO38P/PuR8mxzDobn3C7N/yVL8PHHRe9m+V4C+AYgeJBNk2NqmQRDkbRDeEZaA+99GH15VW5lOlXfGiIqDFXGMpkP3VaeskfW3krAGydpDAttMFlWeP1mJnXozkbaxfhssBJPur6k8bz+TXgHdMQLo1CGyR0fDsQp8awBpA5UwE84y4vwUdnQrCGjEYsiHNZGAy16sdfK0KyyLAOFt13nokm6U2Kd5IeWqRYTjn3gZvt11V8j7rkiFz+4GUu9IId5tBrCQMODpwz7YdQOsDibjMvSOdWta7Sw10n0TeLFeY96x/4364Ikt79zHbch0xv7oqMMBmOv2iUXRYz8SjmyQZ+seTwn57FxPtFntlrqVWpMczRyix1bB1GCkFM3UwesWfvggUnwkbJ55ZYC7JfHEeFqnUBk9mEUJjrB7wFLfUnUc/8hFIE6qSy9boYb80KBw6ilSnmERCVX3Ga8mpXyM9dqWZxs31rmbaEe/5otGKcZ2Sf6AE7fCpgpN5ePHUKqMw66TvABrivd9eUYpcPqsGcTxNuMdoht5FAyQO1w+PwnrTUnvJwamwTHIrA0Everb7PUzsRXqW/tA6EvgNbBU0mCde2/hg8WI29UD5BxDp/f25fpuDC/TsO0d4Ohe9feSH9gUslWVLX8cuFwJ3CAm1/ZqH0BoT6ZA7rRo=
