before_script:
- psql -c 'create database olympics_api_test;' -U postgres
language: ruby
rvm:
- 2.4.1
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
services: postgresql
deploy:
  provider: heroku
  api_key:
    secure: PXCmMRgGmnjYPw3ssDEWGcyeflxvPtxfZZ7pbxh7Nf3kb37V+4+12lrm2V3uIm/QOXdVq1akNz3Ah44ZacPVb/cd6IdXm3nWY+cyz/lAlcUzOPNTLth6GVqdwoSi8FyxJqUz+A2okL5YUfzg8Vlq/uvVzUvEWcll0bzBKOOVtH4z04NuSwYyJbn8Hm6mVG82ljq4B/VDF3vYUkQq2dyPCWbPjqYIJFORafmQV0l8/B1v//6RE5BLDG5cJ7Yg/riEI1zBQwu4iFPKabAGJmjmSgvvQ4sSG2G25uEwPKcwwqDLrccmUPjiiUEseXUQMntoFBUGWzYYfd0c6izGBEVDQpBXZ5S1g9KP8oZ1uwIzgk4SUtY/mmgSZKRvGPfKzmJ55LE+iE2/xP9aWIAAMUtWfgJt++v8fxgKpb/7cNQxzICM/jKvCKuO1eyOUFqvc2Zccq10mMEvXIUpnpPL3KjIDhMzGQf4iaKNpnwDL6l94q19PK3uexhfEfjwfTlDFCE2WCrs7BYUoJrb00gxBUM/e/KYh8Fa06On0Gcp2U2CPylvGHwNPb+YlwjHNGES7AkoJsllOffe5RIfkm1y0jZ+wkvIymoR5UE7zCoLP/85bdLKLCEhCrlmiNLkoVmj/+uPxlKFM6rHznuVF31hinvT2YAd+NrLjOPda2jLNbDGZb0=
  app: olympics-api-jtravers
  on:
    repo: johnktravers/olympics_api
